spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

msclientes:
  url: http://localhost:8083

mscartoes:
  url: http://localhost:8082

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://guest:guest@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes