spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: admin # TODO Change to env-var
      password: admin # TODO Change to env-var

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false