spring:
    application:
        name: msclientes
    profiles:
        active: local

server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://guest:guest@${EUREKA_SERVER}:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}